id: P1FC718A4
initial_creation_type: ocr
source_metadata:
  volumes:
    465dd93a5d004d9ea83ee884f1e13e8e:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: འཕགས་པ་བྱམས་པའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
